# Generated by Django 3.0.5 on 2022-12-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20221212_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
